work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/dataset/data/

global_seed: 341

dataset:
  train_test_split_seed: 55
  train_samples: 414
  test_samples: 177

training:
  num_classes: 3
  learning_rate: 0.001
  num_epochs : 100
  num_workers : 5
  opt_level : 'O1'

model:
  dropout: 0.5

